# Generated by Django 5.2.8 on 2025-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Отчество'),
        ),
    ]
